apiVersion: batch/v1
kind: CronJob
metadata:
  name: schildcafe-barista
  namespace: schildcafe
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: schildcafe-barista
            image: schildwaechter/schildcafe.barista:main
            imagePullPolicy: Always
            env:
            - name: COFFEE_MACHINES
              value: '["http://schildcafe-coffee.schildcafe.svc.cluster.local:1337"]'
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_HOST
              value: "schildcafe-mysql.schildcafe.svc.cluster.local"
            - name: MYSQL_DB
              value: "cafe"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: schildcafe-mysql-secret
                  key: password
            - name: GELF_LOGGING
              value: "TRUE"
            command:
            - python3
            - ./barista.py
          restartPolicy: Never
