apiVersion: apps/v1
kind: Deployment
metadata:
  name: schildcafe-coffee
  namespace: schildcafe
  labels:
    app: schildcafe-coffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schildcafe-coffee
  template:
    metadata:
      labels:
        app: schildcafe-coffee
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: schildcafe-coffee
          image: "schildwaechter/cessda.cafe.coffee.carsten:main"
          imagePullPolicy: Always
          env:
          - name: GELF_LOGGING
            value: "true"
          - name: GIN_MODE
            value: "release"
          ports:
            - containerPort: 1337
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1337
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1337
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: schildcafe-coffee
  namespace: schildcafe
spec:
  ports:
    - port: 1337
  selector:
    app: schildcafe-coffee
  type: NodePort

