apiVersion: v1
kind: PersistentVolume
metadata:
  name: schildcafe-mysql-pv-volume
  namespace: schildcafe
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/schildcafe/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schildcafe-mysql-pv-claim
  namespace: schildcafe
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
