apiVersion: v1
kind: ConfigMap
metadata:
  name: obs-grafana-prometheus-datasource
  labels:
    grafana_datasource: "1"
    app: obs-grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: "http://prometheus-server"
      access: proxy
      isDefault: false
      jsonData:
        timeInterval: "30s"
    - name: Loki
      type: loki
      uid: loki
      url: "http://loki:3100"
      access: proxy
      isDefault: false
      jsonData:
        timeInterval: "30s"
